FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /datacollector

# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore
# Build and publish a release
RUN dotnet publish -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/runtime:9.0
WORKDIR /datacollector
COPY --from=build /datacollector/out .
ENTRYPOINT ["bash", "entrypoint.sh"]
#ENTRYPOINT ["dotnet", "datacollector.dll"]

